### ISSUE TITLE
ReplyのAPI変更

### ISSUE THREAD

**Issue by aibou** [jugyo/rubytter#6]
6/27ごろより，すでに告知されていたみたいですがReplyのAPIに変更があったようです．
- 変更前：/statuses/replies
- 変更後：/statuses/mentions

それに伴い，lib/rubytter.rbの52行目を以下のように変更することで治ります．
- 変更前：replies    /statuses/replies
- 変更後：replies    /statuses/mentions

mentions使えよって話にもなりそうですが，そもそもAPIがなくなったということと既存のサービスにも修整を加える必要があることを考えると，こちらのほうがいいと思うのですがどうでしょう？

**Comment by Sixeight** [comment]
ありがとうございます!

#7 に移行します。
