### ISSUE TITLE
rubytter 1.5.0 gem package seems empty.

### ISSUE THREAD

**Issue by id774** [jugyo/rubytter#9]
$ ls rubytter-1.4.2/ 
History.txt  README.rdoc  Rakefile  VERSION  examples  lib  spec
$ ls rubytter-1.5.0/
$

**Comment by jugyo** [comment]
I'm so sorry… I've just released the not empty version!
Please use 1.5.1

**Comment by id774** [comment]
I confirmed. Thanks.
